/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.DeliveryAgent;

import Business.Business.EcoSystem;
import Business.DB4OUtil.DB4OUtil;
import Business.DistributionCenter.DistributionCenterDirectory;
import Business.Employee.EmployeeDirectory;
import Business.Enterprise.Item;
import Business.Enterprise.Store;
import Business.UserAccount.UserAccountDirectory;
import java.awt.CardLayout;
import java.math.BigDecimal;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author 加藤鹰
 */
public class CreateDeliveryCenterJPanel extends javax.swing.JPanel {
    private EcoSystem system; 
    private Store store;
    private EcoSystem ecoSystem;
    private DistributionCenterDirectory distributionCenterDirectory;
    private EmployeeDirectory employeeDirectory;
    private UserAccountDirectory userAccountDirectory;
    private JPanel panel;
    private JPanel workPanel;
    /**
     * Creates new form CreateDeliveryCenterJPanel
     */
    public CreateDeliveryCenterJPanel() {
        initComponents();
    }

    CreateDeliveryCenterJPanel(EcoSystem system, DeliveryAgentJPanel aThis, JPanel createPanel, Store store) {
       initComponents();
        this.system = system;
        this.panel = panel;
        this.workPanel = createPanel;
        this.store = store;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namejLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelphoneNumber = new javax.swing.JLabel();
        AddressjLabel4 = new javax.swing.JLabel();
        NamejTextField1 = new javax.swing.JTextField();
        PhoneNumberjTextField2 = new javax.swing.JTextField();
        AddressjTextField3 = new javax.swing.JTextField();
        UserNamejTextField3 = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        PassWordjTextField4 = new javax.swing.JTextField();
        jLabelphoneNumber1 = new javax.swing.JLabel();
        AddressjLabel5 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        namejLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelphoneNumber2 = new javax.swing.JLabel();
        AddressjLabel6 = new javax.swing.JLabel();
        NamejTextField2 = new javax.swing.JTextField();
        PhoneNumberjTextField3 = new javax.swing.JTextField();
        AddressjTextField4 = new javax.swing.JTextField();
        UserNamejTextField4 = new javax.swing.JTextField();
        cancelButton1 = new javax.swing.JButton();
        PassWordjTextField5 = new javax.swing.JTextField();
        jLabelphoneNumber3 = new javax.swing.JLabel();
        AddressjLabel7 = new javax.swing.JLabel();
        btnCreate1 = new javax.swing.JButton();
        cancelButton2 = new javax.swing.JButton();
        btnCreate3 = new javax.swing.JButton();
        jLabelphoneNumber4 = new javax.swing.JLabel();
        AddressjLabel8 = new javax.swing.JLabel();
        NamejTextField3 = new javax.swing.JTextField();
        PhoneNumberjTextField4 = new javax.swing.JTextField();
        AddressjTextField5 = new javax.swing.JTextField();
        UserNamejTextField5 = new javax.swing.JTextField();
        PassWordjTextField6 = new javax.swing.JTextField();
        TitlejLabel1 = new javax.swing.JLabel();
        jLabelphoneNumber5 = new javax.swing.JLabel();
        AddressjLabel9 = new javax.swing.JLabel();
        namejLabel4 = new javax.swing.JLabel();
        cancelButton3 = new javax.swing.JButton();
        btnCreate4 = new javax.swing.JButton();

        namejLabel2.setText("Name");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create DeliveryMan Account");

        jLabelphoneNumber.setText("PhoneNumber");

        AddressjLabel4.setText("Adddress");

        NamejTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamejTextField1ActionPerformed(evt);
            }
        });

        PhoneNumberjTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNumberjTextField2ActionPerformed(evt);
            }
        });

        AddressjTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressjTextField3ActionPerformed(evt);
            }
        });

        UserNamejTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNamejTextField3ActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabelphoneNumber1.setText("UserName");

        AddressjLabel5.setText("PassWord");

        btnCreate.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        namejLabel3.setText("Name");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Create DeliveryMan Account");

        jLabelphoneNumber2.setText("PhoneNumber");

        AddressjLabel6.setText("Adddress");

        NamejTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamejTextField2ActionPerformed(evt);
            }
        });

        PhoneNumberjTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNumberjTextField3ActionPerformed(evt);
            }
        });

        AddressjTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressjTextField4ActionPerformed(evt);
            }
        });

        UserNamejTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNamejTextField4ActionPerformed(evt);
            }
        });

        cancelButton1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        cancelButton1.setText("Cancel");
        cancelButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButton1ActionPerformed(evt);
            }
        });

        jLabelphoneNumber3.setText("UserName");

        AddressjLabel7.setText("PassWord");

        btnCreate1.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        btnCreate1.setText("Create");
        btnCreate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreate1ActionPerformed(evt);
            }
        });

        cancelButton2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        cancelButton2.setText("Cancel");
        cancelButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButton2ActionPerformed(evt);
            }
        });

        btnCreate3.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        btnCreate3.setText("Create");
        btnCreate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreate3ActionPerformed(evt);
            }
        });

        jLabelphoneNumber4.setText("PhoneNumber");

        AddressjLabel8.setText("Adddress");

        PhoneNumberjTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNumberjTextField4ActionPerformed(evt);
            }
        });

        AddressjTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressjTextField5ActionPerformed(evt);
            }
        });

        UserNamejTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNamejTextField5ActionPerformed(evt);
            }
        });

        TitlejLabel1.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        TitlejLabel1.setText("Create DistributionCenter Account");

        jLabelphoneNumber5.setText("UserName");

        AddressjLabel9.setText("PassWord");

        namejLabel4.setText("Name");

        cancelButton3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        cancelButton3.setText("Cancel");
        cancelButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButton3ActionPerformed(evt);
            }
        });

        btnCreate4.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        btnCreate4.setText("Create");
        btnCreate4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreate4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cancelButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(109, 109, 109)
                                        .addComponent(namejLabel4))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(AddressjLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelphoneNumber4, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(NamejTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                        .addComponent(PhoneNumberjTextField4))
                                    .addComponent(AddressjTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCreate4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelphoneNumber5)
                                            .addComponent(AddressjLabel9))
                                        .addGap(72, 72, 72)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(UserNamejTextField5)
                                            .addComponent(PassWordjTextField6))))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(77, 77, 77)
                            .addComponent(TitlejLabel1))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitlejLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namejLabel4)
                    .addComponent(NamejTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneNumberjTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelphoneNumber4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddressjLabel8)
                    .addComponent(AddressjTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserNamejTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelphoneNumber5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PassWordjTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddressjLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreate4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton3))
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NamejTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamejTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamejTextField1ActionPerformed

    private void PhoneNumberjTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNumberjTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNumberjTextField2ActionPerformed

    private void AddressjTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressjTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressjTextField3ActionPerformed

    private void UserNamejTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNamejTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNamejTextField3ActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.workPanel.remove(this);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        if(NamejTextField1.getText().isEmpty() || PhoneNumberjTextField2.getText().isEmpty() || AddressjTextField3.getText().isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Fields cannot be left empty");
            return;
        }

        String DeliveryCenterName = NamejTextField1.getText();

        String phoneNumber = PhoneNumberjTextField2.getText();

        for(DistributionCenter distributionCenterr : distributionCenterDirectory.getDistributionCenterDirectory()) {
            if(distributionCenterr.getPhoneNumber().equals(phoneNumber)) {
                JOptionPane.showMessageDialog(null, "Phone Number already exists");
                return;
            }
        }

        String address = AddressjTextField3.getText();
        String userName = UserNamejTextField3.getText();
        String password = PassWordjTextField4.getText();

        for(UserAccount account : ecoSystem.getUserAccountDirectory().getUserAccountList()) {
            if(account.getUsername().equals(userName)) {
                JOptionPane.showMessageDialog(null, "Username Already exists");
                return;
            }
        }

        // make the new add distributionCenter to former

        ecoSystem.getDistributionCenterDirectory().newDistributionCenter(DeliveryCenterName, address, phoneNumber);
        //  getRestaurantDirectory().newRestaurant(DeliveryCenterName, address, managerName, phoneNumber);

        Employee employee = ecoSystem.getEmployeeDirectory().createEmployee(DeliveryCenterName);
        UserAccount userAccount = ecoSystem.getUserAccountDirectory().createUserAccount(userName, password, employee, new DeliveryCenterRole());

        JOptionPane.showMessageDialog(null, "DistributionCenter Created");
    }//GEN-LAST:event_btnCreateActionPerformed

    private void NamejTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamejTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamejTextField2ActionPerformed

    private void PhoneNumberjTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNumberjTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNumberjTextField3ActionPerformed

    private void AddressjTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressjTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressjTextField4ActionPerformed

    private void UserNamejTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNamejTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNamejTextField4ActionPerformed

    private void cancelButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButton1ActionPerformed
        this.workPanel.remove(this);
    }//GEN-LAST:event_cancelButton1ActionPerformed

    private void btnCreate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreate1ActionPerformed
        // TODO add your handling code here:
        if(NamejTextField1.getText().isEmpty() || PhoneNumberjTextField2.getText().isEmpty() || AddressjTextField3.getText().isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Fields cannot be left empty");
            return;
        }

        String DeliveryCenterName = NamejTextField1.getText();

        String phoneNumber = PhoneNumberjTextField2.getText();

        for(DistributionCenter distributionCenterr : distributionCenterDirectory.getDistributionCenterDirectory()) {
            if(distributionCenterr.getPhoneNumber().equals(phoneNumber)) {
                JOptionPane.showMessageDialog(null, "Phone Number already exists");
                return;
            }
        }

        String address = AddressjTextField3.getText();
        String userName = UserNamejTextField3.getText();
        String password = PassWordjTextField4.getText();

        for(UserAccount account : ecoSystem.getUserAccountDirectory().getUserAccountList()) {
            if(account.getUsername().equals(userName)) {
                JOptionPane.showMessageDialog(null, "Username Already exists");
                return;
            }
        }

        // make the new add distributionCenter to former

        ecoSystem.getDistributionCenterDirectory().newDistributionCenter(DeliveryCenterName, address, phoneNumber);
        //  getRestaurantDirectory().newRestaurant(DeliveryCenterName, address, managerName, phoneNumber);

        Employee employee = ecoSystem.getEmployeeDirectory().createEmployee(DeliveryCenterName);
        UserAccount userAccount = ecoSystem.getUserAccountDirectory().createUserAccount(userName, password, employee, new DeliveryCenterRole());

        JOptionPane.showMessageDialog(null, "DistributionCenter Created");
    }//GEN-LAST:event_btnCreate1ActionPerformed

    private void PhoneNumberjTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNumberjTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNumberjTextField4ActionPerformed

    private void AddressjTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressjTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressjTextField5ActionPerformed

    private void UserNamejTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNamejTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNamejTextField5ActionPerformed

    private void cancelButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButton2ActionPerformed
        this.workPanel.remove(this);
    }//GEN-LAST:event_cancelButton2ActionPerformed

    private void btnCreate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreate3ActionPerformed
        // TODO add your handling code here:
        if(NamejTextField1.getText().isEmpty() || PhoneNumberjTextField2.getText().isEmpty() || AddressjTextField3.getText().isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Fields cannot be left empty");
            return;
        }

        String DeliveryCenterName = NamejTextField1.getText();

        String phoneNumber = PhoneNumberjTextField2.getText();

        for(DistributionCenter distributionCenterr : distributionCenterDirectory.getDistributionCenterDirectory()) {
            if(distributionCenterr.getPhoneNumber().equals(phoneNumber)) {
                JOptionPane.showMessageDialog(null, "Phone Number already exists");
                return;
            }
        }

        String address = AddressjTextField3.getText();
        String userName = UserNamejTextField3.getText();
        String password = PassWordjTextField4.getText();

        for(UserAccount account : ecoSystem.getUserAccountDirectory().getUserAccountList()) {
            if(account.getUsername().equals(userName)) {
                JOptionPane.showMessageDialog(null, "Username Already exists");
                return;
            }
        }

        // make the new add distributionCenter to former

        ecoSystem.getDistributionCenterDirectory().newDistributionCenter(DeliveryCenterName, address, phoneNumber);
        //  getRestaurantDirectory().newRestaurant(DeliveryCenterName, address, managerName, phoneNumber);

        Employee employee = ecoSystem.getEmployeeDirectory().createEmployee(DeliveryCenterName);
        UserAccount userAccount = ecoSystem.getUserAccountDirectory().createUserAccount(userName, password, employee, new DeliveryCenterRole());

        JOptionPane.showMessageDialog(null, "DistributionCenter Created");
    }//GEN-LAST:event_btnCreate3ActionPerformed

    private void cancelButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButton3ActionPerformed
        this.workPanel.remove(this);
    }//GEN-LAST:event_cancelButton3ActionPerformed

    private void btnCreate4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreate4ActionPerformed
        // TODO add your handling code here:
        if(NamejTextField1.getText().isEmpty() || PhoneNumberjTextField2.getText().isEmpty() || AddressjTextField3.getText().isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Fields cannot be left empty");
            return;
        }

        String DeliveryCenterName = NamejTextField1.getText();

        String phoneNumber = PhoneNumberjTextField2.getText();

        for(DistributionCenter distributionCenterr : distributionCenterDirectory.getDistributionCenterDirectory()) {
            if(distributionCenterr.getPhoneNumber().equals(phoneNumber)) {
                JOptionPane.showMessageDialog(null, "Phone Number already exists");
                return;
            }
        }

        String address = AddressjTextField3.getText();
        String userName = UserNamejTextField3.getText();
        String password = PassWordjTextField4.getText();

        for(UserAccount account : ecoSystem.getUserAccountDirectory().getUserAccountList()) {
            if(account.getUsername().equals(userName)) {
                JOptionPane.showMessageDialog(null, "Username Already exists");
                return;
            }
        }

        // make the new add distributionCenter to former

        ecoSystem.getDistributionCenterDirectory().newDistributionCenter(DeliveryCenterName, address, phoneNumber);
        //  getRestaurantDirectory().newRestaurant(DeliveryCenterName, address, managerName, phoneNumber);

        Employee employee = ecoSystem.getEmployeeDirectory().createEmployee(DeliveryCenterName);
        UserAccount userAccount = ecoSystem.getUserAccountDirectory().createUserAccount(userName, password, employee, new DeliveryCenterRole());

        JOptionPane.showMessageDialog(null, "DistributionCenter Created");
    }//GEN-LAST:event_btnCreate4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressjLabel4;
    private javax.swing.JLabel AddressjLabel5;
    private javax.swing.JLabel AddressjLabel6;
    private javax.swing.JLabel AddressjLabel7;
    private javax.swing.JLabel AddressjLabel8;
    private javax.swing.JLabel AddressjLabel9;
    private javax.swing.JTextField AddressjTextField3;
    private javax.swing.JTextField AddressjTextField4;
    private javax.swing.JTextField AddressjTextField5;
    private javax.swing.JTextField NamejTextField1;
    private javax.swing.JTextField NamejTextField2;
    private javax.swing.JTextField NamejTextField3;
    private javax.swing.JTextField PassWordjTextField4;
    private javax.swing.JTextField PassWordjTextField5;
    private javax.swing.JTextField PassWordjTextField6;
    private javax.swing.JTextField PhoneNumberjTextField2;
    private javax.swing.JTextField PhoneNumberjTextField3;
    private javax.swing.JTextField PhoneNumberjTextField4;
    private javax.swing.JLabel TitlejLabel1;
    private javax.swing.JTextField UserNamejTextField3;
    private javax.swing.JTextField UserNamejTextField4;
    private javax.swing.JTextField UserNamejTextField5;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnCreate1;
    private javax.swing.JButton btnCreate3;
    private javax.swing.JButton btnCreate4;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton cancelButton1;
    private javax.swing.JButton cancelButton2;
    private javax.swing.JButton cancelButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelphoneNumber;
    private javax.swing.JLabel jLabelphoneNumber1;
    private javax.swing.JLabel jLabelphoneNumber2;
    private javax.swing.JLabel jLabelphoneNumber3;
    private javax.swing.JLabel jLabelphoneNumber4;
    private javax.swing.JLabel jLabelphoneNumber5;
    private javax.swing.JLabel namejLabel2;
    private javax.swing.JLabel namejLabel3;
    private javax.swing.JLabel namejLabel4;
    // End of variables declaration//GEN-END:variables
}
